name: fpinger
base: core18
#title: Bitrix24 Host checker app
architectures:
  - build-on: amd64
  - build-on: armhf
  - build-on: arm64
version: '2021.10.18'
summary: Bitrix24 Host checker app # 79 char long summary
description: |
  This app will check hosts for availability for Bitrix24
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
icon: ./logo.png

apps:    
  fpinger:
    command: run.sh
    daemon: simple
    restart-condition: always
    plugs: [network, network-bind, network-observe]

parts:
  assets:
    source: assets/
    plugin: dump
  libs:
    plugin: dump
    source:
      - on amd64: https://b24auth.blob.core.windows.net/fpinger/1os.pinger.x64.zip
      - on armhf: https://b24auth.blob.core.windows.net/fpinger/1os.pinger.arm.zip
      - on arm64: https://b24auth.blob.core.windows.net/fpinger/1os.pinger.arm64.zip
    source-type: zip
    stage-packages:
      - libqt5gui5
      - zlib1g
    after: [assets]
  
